---
- hosts: all
  become: true
  vars:
    logstash_inputs:
      - type: redis
        batch_count: 1000
        host: redis
        threads: 2
    logstash_outputs:
      - output: elasticsearch
        hosts: 'elasticsearch:9200'
        flush_size: 5000
    logstash_server_fqdn: redis
    skip_validation: true
  roles:
    - role: ansible-logstash
    - role: ansible-elk-processor
  tasks:
